# Generated by Django 4.1.1 on 2022-10-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
